# Generated by Django 4.0.6 on 2022-08-25 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_profile_description_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voicemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice.voice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
