# Generated by Django 4.0.6 on 2022-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_script'),
        ('accounts', '0008_voicemark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemark',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='voicemark',
            name='bookmark',
            field=models.ManyToManyField(blank=True, to='voice.voice'),
        ),
    ]
