# Generated by Django 4.0.6 on 2022-08-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
