# Generated by Django 4.0.6 on 2022-11-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(choices=[('감탄사', '감탄사'), ('관형사', '관형사'), ('대명사', '대명사'), ('동사', '동사'), ('명사', '명사'), ('부사', '부사'), ('수관', '수관'), ('수사', '수사'), ('어미', '어미'), ('의존 명사', '의존 명사'), ('조사', '조사'), ('형용사', '형용사'), ('품사 없음', '품사 없음')], max_length=30)),
            ],
        ),
    ]
