# Generated by Django 4.0.6 on 2022-11-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='word',
        ),
    ]
