# Generated by Django 4.0.6 on 2022-11-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('강원도', '강원도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('제주특별자치도', '제주특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('광주광역시', '광주광역시'), ('대구광역시', '대구광역시'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('서울특별시', '서울특별시'), ('인천광역시', '인천광역시'), ('대전광역시', '대전광역시'), ('경기도', '경기도'), ('세종특별자치시', '세종특별자치시')], max_length=30)),
                ('seoul', models.CharField(max_length=50)),
                ('mean', models.CharField(default='', max_length=500)),
                ('pos', models.CharField(choices=[('감탄사', '감탄사'), ('관형사', '관형사'), ('대명사', '대명사'), ('동사', '동사'), ('명사', '명사'), ('부사', '부사'), ('수관', '수관'), ('수사', '수사'), ('어미', '어미'), ('의존 명사', '의존 명사'), ('조사', '조사'), ('형용사', '형용사'), ('품사 없음', '품사 없음')], max_length=30)),
            ],
        ),
    ]
