# Generated by Django 4.0.6 on 2022-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='mean',
            new_name='ex_seoul',
        ),
        migrations.RemoveField(
            model_name='word',
            name='pos',
        ),
        migrations.AddField(
            model_name='word',
            name='ex_word',
            field=models.CharField(default='', max_length=500),
        ),
    ]
