# Generated by Django 4.0.6 on 2022-08-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('강원도', '강원도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('제주특별자치도', '제주특별자치도'), ('충청북도', '충청남도'), ('광주광역시', '광주광역시'), ('대구광역시', '대구광역시'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('서울특별시', '서울특별시'), ('인천광역시', '인천광역시'), ('대전광역시', '대전광역시'), ('경기도', '경기도'), ('세종특별자치시', '세종특별자치시')], max_length=30)),
                ('situation', models.CharField(blank=True, choices=[('연애/결혼', '연애/결혼'), ('시사/정치', '시사/정치'), ('일상', '일상'), ('취미', '취미'), ('자기개발', '자기개발'), ('여행', '여행')], max_length=30)),
                ('talker', models.CharField(blank=True, choices=[('유아/아동', '유아/아동'), ('초등학생', '초등학생'), ('중학생', '중학생'), ('고등학생', '고등학생'), ('20/30대', '20/30대'), ('40/50대', '40/50대'), ('60대~', '60대~')], max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('남', '남'), ('여', '여'), ('혼성', '혼성')], max_length=30)),
                ('views', models.IntegerField(default=0)),
                ('memo', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
