# Generated by Django 4.0.6 on 2022-08-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_voice_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='talker',
            new_name='talker_age',
        ),
        migrations.RenameField(
            model_name='voice',
            old_name='gender',
            new_name='talker_gender',
        ),
    ]
