# Generated by Django 4.0.6 on 2022-08-25 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_rename_talker_voice_talker_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('voice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voice.voice')),
            ],
        ),
    ]
