# Generated by Django 4.0.6 on 2022-09-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='region',
            field=models.CharField(choices=[('강원도', '강원도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('제주특별자치도', '제주특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('광주광역시', '광주광역시'), ('대구광역시', '대구광역시'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('서울특별시', '서울특별시'), ('인천광역시', '인천광역시'), ('대전광역시', '대전광역시'), ('경기도', '경기도'), ('세종특별자치시', '세종특별자치시')], max_length=30),
        ),
    ]
