# Generated by Django 4.0.6 on 2022-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_alter_voice_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
