# Generated by Django 4.0.6 on 2022-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0006_voice_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='text',
            field=models.FileField(blank=True, upload_to='script'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='audio',
            field=models.FileField(blank=True, upload_to='voice'),
        ),
    ]
