# Generated by Django 4.0.6 on 2022-09-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0007_script_text_alter_voice_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='text_string',
            field=models.TextField(blank=True),
        ),
    ]
