# Generated by Django 4.0.6 on 2022-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0009_remove_script_text_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='text',
            field=models.FileField(upload_to='script'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='audio',
            field=models.FileField(upload_to='voice'),
        ),
    ]
