# Generated by Django 4.0.6 on 2022-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0011_voice_script_delete_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
