# Generated by Django 4.0.6 on 2022-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0012_voice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='script_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
