# Generated by Django 4.0.6 on 2022-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0014_alter_voice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
